language: ruby

services:
  - postgresql

before_script:
  - psql -c 'CREATE DATABASE chitter_test;' -U postgres
  - psql -U postgres -d chitter_test -f db/migrations/02_setup_user_table.sql
  - psql -U postgres -d chitter_test -f db/migrations/03.setup_peep_table.sql

script:
  - bundle exec rspec
